
# ==============================================
# Docker Compose - Contabilidade Igrejinha Backend
# ==============================================


services:
  # ==============================================
  # Backend API
  # ==============================================
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: contabil-backend
    ports:
      - "3001:3001"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=development
      - OPENSSL_CONF=/dev/null
      # Variáveis do banco de dados
      - DATABASE_URL=postgresql://contabil_user:contabil_pass@postgres:5432/contabil_db?schema=public
      - POSTGRES_DB=contabil_db
      - POSTGRES_USER=contabil_user
      - POSTGRES_PASSWORD=contabil_pass
      # Variáveis do Redis
      - REDIS_URL=redis://redis:6379
      # Variáveis JWT
      - JWT_SECRET=sua_chave_secreta_jwt_muito_segura_aqui_2024
      - JWT_EXPIRES_IN=7d
      - JWT_REFRESH_SECRET=sua_chave_refresh_jwt_muito_segura_aqui_2024
      - JWT_REFRESH_EXPIRES_IN=30d
    volumes:
      - .:/app
      - /app/node_modules
      - uploads_data:/app/uploads
      - logs_data:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - contabil-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ==============================================
  # PostgreSQL Database
  # ==============================================
  postgres:
    image: postgres:15-alpine
    container_name: contabil-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=contabil_db
      - POSTGRES_USER=contabil_user
      - POSTGRES_PASSWORD=contabil_pass
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - contabil-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contabil_user -d contabil_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ==============================================
  # Redis Cache
  # ==============================================
  redis:
    image: redis:7-alpine
    container_name: contabil-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - contabil-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s

  # ==============================================
  # PgAdmin (Database Management)
  # ==============================================
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: contabil-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@contabilidadeigrejinha.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - contabil-network
    restart: unless-stopped

  # ==============================================
  # Mailhog (Email Testing)
  # ==============================================
  mailhog:
    image: mailhog/mailhog:latest
    container_name: contabil-mailhog
    ports:
      - "${MAILHOG_SMTP_PORT:-1025}:1025"  # SMTP
      - "${MAILHOG_WEB_PORT:-8025}:8025"  # Web UI
    networks:
      - contabil-network
    restart: unless-stopped

# ==============================================
# Volumes
# ==============================================
volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  redis_data:
    driver: local
  uploads_data:
    driver: local
  logs_data:
    driver: local

# ==============================================
# Networks
# ==============================================
networks:
  contabil-network:
    driver: bridge